Kh UI 23 create label k UI atom
kheironCo/kheiron-ui pull request #13
Opened 2024-05-05 19:15 UTC by gastonjau

2024-05-05 23:37 UTC, gastonjau commented
![image](https://github.com/kheironCo/kheiron-ui/assets/132623094/694a69da-e69e-42bb-9fb1-fa524015c2b9)

2024-05-06 02:42 UTC, MarcosRehtanz requested changes

2024-05-06 02:42 UTC, MarcosRehtanz commented on src/molecules/LabelKUI/index.tsx
> +    <div css={((align == "left") && AlinearLeft)||((align == "center") && AlinearCenter) || ((align == "right") && AlinearRight)}>
No utilizar las etiqutas html. Utiliza `AtomDiv`

2024-05-06 02:42 UTC, MarcosRehtanz commented on src/molecules/LabelKUI/index.tsx
> +    <div css={((align == "left") && AlinearLeft)||((align == "center") && AlinearCenter) || ((align == "right") && AlinearRight)}>
En el root deben ir los estilos de las posiciones.
Utiliza `display: flex` y `flexDirection:` para que quede el label en las diferentes positiones.
```
flexDirection: row;
flexDirection: row-reverse;
flexDirection: column;
flexDirection: column-reverse;
```

2024-05-06 02:42 UTC, MarcosRehtanz commented on src/molecules/LabelKUI/index.tsx
> +    {
La alineación es para el label cuando está arriba o debajo del children,
`text-align: left` `text-align: center` `text-align: right`

![image](https://github.com/kheironCo/kheiron-ui/assets/135645576/934ba2d9-d8c6-4c31-bcf4-3fa76f934ee0)

2024-05-06 02:42 UTC, MarcosRehtanz commented on src/molecules/UserProfileCardKUI/index.tsx
>  import { UserProfileCardRoot, UserProfileCardHead, UserProfileCardBody } from './styles';
Se subió código en conflictivo sin resolver.
Corregirlo

2024-05-07 01:46 UTC, MarcosRehtanz requested changes
### Atención

> Antes de comenzar ejecutar el siguiente comando
```
pnpm husky
```

2024-05-07 01:46 UTC, MarcosRehtanz commented on src/molecules/LabelKUI/styles.css
Eliminar archivos innecesarios

2024-05-07 01:46 UTC, MarcosRehtanz commented on src/molecules/LabelKUI/index.tsx
> +type AlignType = "left" | "center" | "right";
crear un archivo type para los tipos.

2024-05-07 01:46 UTC, MarcosRehtanz commented on src/molecules/LabelKUI/index.tsx
> +type AlignType = "left" | "center" | "right";
Agregar 2 types nuevos para simplificar el código. `PositionStyleType` y `AlignStyleType`
Ejemplo de Position:
```
import { SerializedStyles } from '@emotion/react';

export type PositionType = "top" | "bottom" | "left" | "right";
export type PositionStyleType = Record<PositionType, SerializedStyles>
```

_Esto lo que hace es que las KEYS que necesita el objeto son las de PositionType, y su valor será el SerializedStyles de emotion/react_

2024-05-07 01:46 UTC, MarcosRehtanz commented on src/molecules/LabelKUI/styles.tsx
> +`;
Aqui también simplificaremos el código utilizando los tipos creados
```
import { PositionStyleType } from './type.ts';

export const PositionStyle: PositionStyleType = {
  top: css``,
  bottom: css``,
  left: css``,
  right: css``,
}
```
_En lugar de exportar 7 estilos exportaras 2 objetos de arreglos gracias al PositionStyleType_
_Por haberle definido el type ahora te avisa que valores necesitas y te están haciendo falta_

2024-05-07 01:46 UTC, MarcosRehtanz commented on src/molecules/LabelKUI/index.tsx
> +        <AtomDiv css={((position == "top") && PositionTop) ||((position == "bottom") && PositionBottom) || ((position == "left") && PositionLeft) || ((position == "right") && PositionRight)}>
Importar PositionStyle y utilizarlo de la siguiente manera:
```
import { PositionStyle } from 'styles.tsx';

( { position="top" } )=>(
  <AtomDiv css={ PositionStyle[ position ] }></AtomDiv>
)
```
_Ahora los estilos al estar definidos con los nuevos type simplemente tenemos que renderizar el estilo solicitado_

2024-05-07 20:25 UTC, MarcosRehtanz approved these changes

2024-05-08 21:34 UTC, merged