Kh UI 22 create password k UI atom
kheironCo/kheiron-ui pull request #15
Opened 2024-05-08 20:50 UTC by gastonjau

:)

2024-05-08 20:51 UTC, gastonjau commented
![image](https://github.com/kheironCo/kheiron-ui/assets/132623094/f0b61cef-6899-4139-96c8-d92d581e2f97)

2024-05-08 22:23 UTC, MarcosRehtanz requested changes

2024-05-08 22:23 UTC, MarcosRehtanz commented on src/atom/PasswordInputKUI/PasswordInputKUI.stories.tsx
storybook probee de types para definir la estructura de los datos.
Imitar del archivo `CheckKUI.stories.tsx`

2024-05-08 22:23 UTC, MarcosRehtanz commented on src/atom/PasswordInputKUI/index.tsx
> +import { IconEye2 } from '../../icons/iconPasswordChecked';
Corregir las importaciones.
deben de colocarse en el archivo index de la capeta icons y importarlas desde ahí.
`import { /**/ } from '../../icons'`

2024-05-08 22:23 UTC, MarcosRehtanz commented on src/atom/PasswordInputKUI/index.tsx
> +  const [_value, _setValue] = useState(' ');
debe iniciarse como un string vacío. `useState('')`

2024-05-08 22:23 UTC, MarcosRehtanz commented on src/atom/PasswordInputKUI/index.tsx
> +      <AtomInput onChange={handleChange} value={_value} type={!activo ? 'password' : 'text'} />
evitar usar la negación de ser posíble.
`activo ? 'text' : 'password'`

2024-05-08 22:23 UTC, MarcosRehtanz commented on src/atom/PasswordInputKUI/index.tsx
> +  const [activo, setActivo] = useState(false);
usar convenciones en ingles
cambiarle el nombre del nombre de la variable a:
`[visible, setVisible]`

2024-05-08 22:23 UTC, MarcosRehtanz commented on src/icons/iconPassword/OjoAbierto.png
Eliminar .png

2024-05-08 22:23 UTC, MarcosRehtanz commented on src/atom/PasswordInputKUI/index.tsx
> +    <AtomDiv css={DivStyle}>
falta en nombre de las clases con la convención asignada

2024-05-08 22:23 UTC, MarcosRehtanz commented on src/icons/iconPassword/index.tsx
> +export const IconEye = () => (
debe recibir minimo 2 parametros: `size` y `color` este componente debe ser personalizable
debe tener valores por default, _toma del mismo svg su _**hight** y **width** para size → `size='24'` (no se precisa aclarar los pixels) y _tomas del fill su valor para el color_ `color='#5f6368'`

2024-05-08 22:23 UTC, MarcosRehtanz commented on src/icons/iconPassword/index.tsx
> +    height="24px"
el height y el width serán igual al valor del size
`height={size}`

2024-05-08 22:23 UTC, MarcosRehtanz commented on src/icons/iconPassword/index.tsx
> +    fill="#5f6368"
el fill debe ser igual al color 
`fill={color}`

2024-05-08 22:23 UTC, MarcosRehtanz commented on src/icons/iconPasswordChecked/OjoAbierto.png
Eliminar `.png`

2024-05-08 22:23 UTC, MarcosRehtanz commented on src/icons/iconPasswordChecked/index.tsx
Los `icons` tambien deben tener su archivo `stories`

2024-05-08 22:23 UTC, MarcosRehtanz commented on src/icons/iconPasswordChecked/index.tsx
Aplicar las mismas correcciones que en el otro icon

2024-05-08 22:23 UTC, MarcosRehtanz commented on src/icons/iconPasswordChecked/index.tsx
> +export const IconEye2 = () => (
nombre del componente cambiarlo a: `IconEye` y `IconEyeClosed` respectivamente

2024-05-08 22:23 UTC, MarcosRehtanz commented on src/icons/iconPasswordChecked/index.tsx
> +export const IconEye2 = () => (
En nombre de la carpeta tambien debe corresponder al nombre del archivo

2024-05-11 02:14 UTC, MarcosRehtanz approved these changes
Good Job

2024-05-11 02:14 UTC, merged