Primer commit de CheckboxKUI
kheironCo/kheiron-ui pull request #16
Opened 2024-05-09 18:56 UTC by gastonjau

2024-05-18 23:37 UTC, MarcosRehtanz requested changes
También falta captura de las evidencias

2024-05-18 23:37 UTC, MarcosRehtanz commented on src/molecules/LabelKUI/index.tsx
> +        <AtomLabel className={className} css={AlignStyle[align]} htmlFor={htmlFor}>
El className que estas recibiendo por parametro colocarlo en el Div del root.
Aqui colocarle su propio div con las características ya utilizadas

2024-05-18 23:37 UTC, MarcosRehtanz commented on src/molecules/LabelKUI/index.tsx
>      <AtomDiv>
Eliminar Div sobrante

2024-05-18 23:37 UTC, MarcosRehtanz commented on src/molecules/InputFieldCheckboxKUI/index.tsx
> +        className={'KUI-checkbox-label'}
colocar el texto solo como string, no precisa las llaves `className=""`

2024-05-19 00:10 UTC, MarcosRehtanz requested changes

2024-05-19 00:10 UTC, MarcosRehtanz commented on src/molecules/InputFieldCheckboxKUI/index.tsx
> +  };
LabelKUI y CheckKUI ya contienen esos parámetros, no debes de volver a declararlos
ya estan declarados en sus props y es por eso que las estás concatenando

LabelKUIProps = {
  label: string;
  position?: PositionType;
  align?: AlignType;
  htmlFor?: string;
  children: ReactElement;
  className?: string;
};

2024-05-20 14:51 UTC, gastonjau commented
![image](https://github.com/kheironCo/kheiron-ui/assets/132623094/c83b7764-71e3-4941-90c1-11fb5c9db896)

2024-05-20 19:27 UTC, MarcosRehtanz approved these changes

2024-05-20 19:27 UTC, merged