Primer commit radiobutton
kheironCo/kheiron-ui pull request #26
Opened 2024-05-22 16:29 UTC by gastonjau

Agrego radioButton pero el dato que se debe pasar como props es un array con la cantidad de objetos que desees dentro, los cuales deben de contener un name y un value:  {name:"Radio1", value:"valor1"}

2024-05-22 16:30 UTC, gastonjau commented
![image](https://github.com/kheironCo/kheiron-ui/assets/132623094/0315b94c-d115-4671-bc68-07ac7fe02802)

2024-05-23 17:01 UTC, MarcosRehtanz requested changes

2024-05-23 17:01 UTC, MarcosRehtanz commented on src/form/InputFieldRadioCheckKUI/index.tsx
> +  radio: { name: string, value: string }[],
initValue?: string

2024-05-23 17:01 UTC, MarcosRehtanz commented on src/form/InputFieldRadioCheckKUI/index.tsx
> +  const [selectedRadio, setSelectedRadio] = useState<string | null>(null);
`( initValue ?? null )`

2024-05-23 17:01 UTC, MarcosRehtanz commented on src/form/InputFieldRadioCheckKUI/index.tsx
> +                <AtomDiv>
Utilizar el `InputFieldCheckboxKUI` manteniendo la misma lógica

2024-05-23 17:01 UTC, MarcosRehtanz commented on src/form/InputFieldRadioCheckKUI/index.tsx
> +  radio: { name: string, value: string }[],
corregir nombres `radio → items` y `name → label`

2024-05-24 01:50 UTC, gastonjau commented
![image](https://github.com/kheironCo/kheiron-ui/assets/132623094/828160f5-bc7f-49d8-9e50-57571353f817)

2024-05-24 20:30 UTC, gastonjau commented
![image](https://github.com/kheironCo/kheiron-ui/assets/132623094/fb55cd6b-0b67-4630-a185-3a339b321aaf)

2024-05-24 20:30 UTC, gastonjau commented
![image](https://github.com/kheironCo/kheiron-ui/assets/132623094/f876fad5-d2d0-49c6-a3ef-4970d7bb4926)

2024-05-24 23:42 UTC, MarcosRehtanz requested changes

2024-05-24 23:42 UTC, MarcosRehtanz commented on src/form/InputFieldRadioCheckKUI/index.tsx
> +              className={`KUI-input-field-radio-check-${index}`}
corregir el className, si solo dejas la de index sería dificil seleccionarlo
`'KUI-input-field-radio-check-label KUI-input-field-radio-check-label-${index}'`

2024-05-24 23:42 UTC, MarcosRehtanz commented on src/form/InputFieldRadioCheckKUI/index.tsx
> +            <AtomLabel
Se creó el elemento `LabelKUI` para estos casos, como children pasale los elementos como el input y los iconos

2024-05-24 23:42 UTC, MarcosRehtanz commented on src/form/InputFieldRadioCheckKUI/index.tsx
> +            {selectedRadio !== el.value && iconChecked}
en lugar de hacer dos verificaciones colocar un ternario
`(condition) ? true : false`

2024-05-24 23:42 UTC, MarcosRehtanz commented on src/form/InputFieldRadioCheckKUI/index.tsx
> +            ></AtomInput>
Debe ser una sola etiqueta `<AtomInput />`

2024-05-24 23:42 UTC, MarcosRehtanz commented on src/form/InputFieldRadioCheckKUI/index.tsx
> +    <LabelKUI>
hay que pasarle un parametro label para este labelKUI, que será opcional

2024-05-24 23:42 UTC, MarcosRehtanz commented on src/form/InputFieldRadioCheckKUI/index.tsx
> +          <AtomDiv className="KUI-input-field-radio-check-root" key={index}>
Quitar los `AtomDiv` que no sean necesarios

2024-05-24 23:42 UTC, MarcosRehtanz commented on src/form/InputFieldRadioCheckKUI/index.tsx
> +}[];
Quitarle el arreglo. El type solo es el Objeto, indicar que se requiere un Arreglo cuando se necesite

2024-05-24 23:42 UTC, MarcosRehtanz commented on src/form/InputFieldRadioCheckKUI/index.tsx
> +  items: RadioCheckItem;
Aqui debe indicarse que recibe un arreglo de este type `RadioCheckItem[]`

2024-05-27 14:57 UTC, gastonjau commented on src/form/InputFieldRadioCheckKUI/index.tsx
> +            <AtomLabel
En este caso no supe como hacerlo

2024-05-27 14:59 UTC, gastonjau commented on src/form/InputFieldRadioCheckKUI/index.tsx
> +            <AtomLabel
SI cambio el Atom Label por el LabelKUI deja de funcionar

2024-05-28 19:25 UTC, MarcosRehtanz requested changes

2024-05-28 19:25 UTC, MarcosRehtanz commented on src/form/InputFieldRadioCheckKUI/InputFieldRadioCheckKUI.stories.tsx
> +import { IconHeartFilled, IconHeartOutlined } from '@KUI-icons';
utilizar ruta relativa `../../icons`
se eliminaran los alias proximamente

2024-05-28 22:14 UTC, MarcosRehtanz approved these changes

2024-05-28 22:14 UTC, merged