Kh UI 29 create input field textarea k UI
kheironCo/kheiron-ui pull request #27
Opened 2024-05-23 02:09 UTC by Rennerx3

2024-05-23 16:57 UTC, MarcosRehtanz requested changes
Tambien subir una captura de como queda el componente en storybook

2024-05-23 16:57 UTC, MarcosRehtanz commented on src/molecules/InputFieldTextareaKUI/index.tsx
> +export const InputFieldTextareaKUI = ({ label, ...rest }: LabelKUIProps) => {
Aquí debes de crear un type para  este Input, `type InputFieldTextareaKUI` y las debes concatenar las props de ambas etiquetas `= LabelKUIProps & AtomTextAreaProps`.
desestructurar las propiedades de LabelKUI y pasarle sus atributos y el `...rest` que corresponde a textarea pasarlo como lo implementaste

2024-05-23 16:57 UTC, MarcosRehtanz commented on src/molecules/InputFieldTextareaKUI/InputFieldTextareaKUI.stories.tsx
> +    title: 'Molecules/InputFieldTextareaKUI',
corregir el título a `Form/InputFieldTextareaKUI`

2024-05-23 18:30 UTC, Rennerx3 commented
![imagen_2024-05-23_153050602](https://github.com/kheironCo/kheiron-ui/assets/98594881/11cbaa53-85de-424b-8ad0-eeb585250801)

2024-05-24 23:24 UTC, MarcosRehtanz requested changes

2024-05-24 23:24 UTC, MarcosRehtanz commented on src/atom/CheckKUI/index.tsx
> +import { IconCheckBox } from '../../icons';
este archivo tiene conflictos, resolverlos

2024-05-28 21:45 UTC, merged