KHUI-34-Create-TagKUI
kheironCo/kheiron-ui pull request #30
Opened 2024-05-28 22:26 UTC by gastonjau

2024-05-30 20:55 UTC, gastonjau commented
![image](https://github.com/kheironCo/kheiron-ui/assets/132623094/54d6a93e-7a5b-4d16-88fc-718930f39b39)

2024-05-31 17:29 UTC, MarcosRehtanz requested changes

2024-05-31 17:29 UTC, MarcosRehtanz commented on src/utily/TagKUI/types.tsx
> +export type StyledType2 = Record<borderType, SerializedStyles>;
los `Types` no deben ser numerados, deben ser claros en la descripción,
`StyledBorderType`
`StyledBgType`

2024-05-31 17:29 UTC, MarcosRehtanz commented on src/utily/TagKUI/types.tsx
> +export type borderType = 'none' | 'solid' | 'dashed' | 'dotted';
Definir los Type con `PascalCase`

2024-05-31 17:29 UTC, MarcosRehtanz commented on src/utily/TagKUI/types.tsx
> +  label: string;
en lugar de ser un string asignale un `ReactNode`

2024-05-31 17:29 UTC, MarcosRehtanz commented on src/utily/TagKUI/styles.tsx
> +const estilos = css`
mantener la nomenclatura en ingles, en este caso puede ser `general` o `generalStyle`

2024-05-31 17:29 UTC, MarcosRehtanz commented on src/utily/TagKUI/index.tsx
> +  const styleColor = useMemo(() => stylesBackground[color], [color]);
cambiar el nombre de la variable por `styleBackground`, esto ayuda que al tener que hacer modificaciones futuras, si tiene una nomenclatura clara, se sepa que se esta modificando y de que forma afecta al componente

2024-05-31 21:21 UTC, MarcosRehtanz approved these changes

2024-05-31 21:23 UTC, merged