KHUI-36-Create-NotificationKUI
kheironCo/kheiron-ui pull request #42
Opened 2024-06-15 21:38 UTC by jalejotorresm

Para este PR se hicieron los siguientes items:

1. Se creo el elemento AtomSpan para contenedores en linea

2. Se creo el componente NotificationKUI, junto a su hoja de estilos y su archivo de storybook.

3. Se modificó el archivo example/index.tsx, ya que el metodo ReactDOM.render fue marcado por el eslint como codigo antiguo de React.

2024-06-16 00:47 UTC, MarcosRehtanz requested changes

2024-06-16 00:47 UTC, MarcosRehtanz commented on stories/notification/Notifications.stories.tsx
> +};
Agregar stories de los todas las variantes, `Error`, `Info`, `Warn`, `Success`

2024-06-16 00:47 UTC, MarcosRehtanz commented on src/molecules/NotificationKUI/index.tsx
crear la carpeta `notification` en la carpeta `./src` y mover allí el componente

2024-06-16 00:47 UTC, MarcosRehtanz commented on src/molecules/TableKUI/Table.stories.tsx
Eliminar la carpeta `TableKUI` ya que se realizó en otro ticket

2024-06-17 02:30 UTC, jalejotorresm commented
Correcciones realizadas según recomendaciones. Tome la oportunidad para mejorar algunos temas de color en las notificaciones para mejorar la experiencia de usuario.

2024-06-17 04:42 UTC, MarcosRehtanz approved these changes

2024-06-17 04:42 UTC, merged