Kh UI 57 fix avatar
kheironCo/kheiron-ui pull request #59
Opened 2024-07-13 16:44 UTC by brianpadilla3072

2024-07-13 17:56 UTC, MarcosRehtanz requested changes

2024-07-13 17:56 UTC, MarcosRehtanz commented on src/utily/AvatarKUI/styles.tsx
> +  size: { width: string; height: string };
Para los type create una carpeta que se llame `type.ts` ymcolocalos ahí

2024-07-14 06:17 UTC, brianpadilla3072 commented on src/utily/AvatarKUI/styles.tsx
> +  size: { width: string; height: string };
okey

2024-07-14 06:22 UTC, brianpadilla3072 reviewed
listo

2024-07-14 06:37 UTC, MarcosRehtanz requested changes

2024-07-14 06:37 UTC, MarcosRehtanz commented on src/utily/AvatarKUI/index.tsx
> +}: AvatarKUIProps) => {
Quitar los valores por default

2024-07-14 06:45 UTC, brianpadilla3072 commented
![WhatsApp Image 2024-07-14 at 03 00 51](https://github.com/user-attachments/assets/f1e66457-5c5c-44b7-a526-04831d12b755)
![WhatsApp Image 2024-07-14 at 03 01 18](https://github.com/user-attachments/assets/a3e57e1a-6e1f-4ce4-a945-1fb5e52b8076)
![WhatsApp Image 2024-07-14 at 03 02 07](https://github.com/user-attachments/assets/847ec969-fbac-46bd-9383-28a9d4681e9e)

2024-07-14 06:53 UTC, MarcosRehtanz approved these changes

2024-07-14 06:54 UTC, merged