Primer push de SearchBar
kheironCo/kheiron-ui pull request #7
Opened 2024-04-30 23:29 UTC by gastonjau

Estructura de SearchBar sin estilos

2024-05-03 15:35 UTC, gastonjau commented
![image](https://github.com/kheironCo/kheiron-ui/assets/132623094/dec539af-b1dc-43cb-bdc5-ac06e5a3b766)

2024-05-03 19:39 UTC, MarcosRehtanz requested changes

2024-05-03 19:39 UTC, MarcosRehtanz commented on src/element/AtomForm/index.tsx
> +export const AtomForm: React.FC<AtomFormProps & { handleSearch?: () => void }> = ({ className, handleSearch, ...rest }) =>
Deshacer los cambios realizados en este componente, y utilizar la propiedades del html del form `FormHTMLAttributes<HTMLFormElement>` con este tipo se estas asignándole las mismas props.
En este caso en lugar de crear el `handleSearch`  utiliza el `onSubmit` de forma convencional

2024-05-03 19:39 UTC, MarcosRehtanz commented on src/element/AtomInput/index.tsx
> +export const AtomInput: React.FC<AtomInputProps & { handleChange?: (event: React.ChangeEvent<HTMLInputElement>) => void }> = ({ className, handleChange, ...rest }) =>
Deshacer los cambios
Mismo caso que en el `AtomForm` simplemente pasale los parametros utilizando el `onChange`, y no agregandole nuevos parametros

2024-05-04 04:45 UTC, MarcosRehtanz requested changes

2024-05-04 04:45 UTC, MarcosRehtanz commented on src/molecules/SearchBarKUI/SearchBar.stories.tsx
> +    title: 'Organism/SearchBar',
Este componente debe ir como la ruta `Molecule/`

2024-05-04 04:45 UTC, MarcosRehtanz commented on src/molecules/SearchBarKUI/index.tsx
> +export const SearchBarKUI: React.FC<SearchBarKUIProps> = ({ value, handleChange, handleSearch }) => {
asignarle el type a las props en lugar de utilizar el FC

2024-05-04 04:45 UTC, MarcosRehtanz commented on src/molecules/SearchBarKUI/index.tsx
> +  handleSearch?: () => {};
Utilizar `void` cuando no se devuelvan valores en una función
Asignar los siguientes types
```
handleChange?: (e: ChangeEvent<HTMLInputElement>) => void;
handleSearch?: (e: FormEvent<HTMLFormElement>) => void;
```

2024-05-04 04:45 UTC, MarcosRehtanz commented on src/molecules/SearchBarKUI/index.tsx
> +        <AtomButton className='KUI-search-bar-button' css={css(boton)} type="submit">Search</AtomButton>
en la forma que se está trabajando simplemente pasale el valor `css={boton}` y usa convención en ingles `button`

2024-05-04 04:45 UTC, MarcosRehtanz commented on src/molecules/SearchBarKUI/index.tsx
> +        <AtomInput className='KUI-search-bar-input' css={css(input)} onChange={handleChange} value={value} />
Hacer lo mismo de la función intermedia.
Y el value en lugar de recibirlo por parametro crear un `getValue` para solo se pueda obtener el parametro _(Revisar su implementación y uso en `CheckKUI`)_

2024-05-04 04:45 UTC, MarcosRehtanz commented on src/molecules/SearchBarKUI/index.tsx
> +      <AtomForm className='KUI-search-bar-form' onSubmit={handleSearch}>
Manejar la lógica con una función intermedia en caso de que no se pase la función.
```
const _onSubmit = (e: FormEvent<HTMLFormElement>)=>{
  // si existe la función se ejecutará
  if(handleSearch) handleSearch(e);
}
```

2024-05-04 04:45 UTC, MarcosRehtanz commented on src/molecules/UserProfileCardKUI/index.tsx
> +export const UserProfileCardKUI = ({ image= "", head, body }: UserProfileCardKUIProps) => (
Hay varias inconsistencias con el formato y el ESlint.
Eliminar la carpeta `node_modules` con el comando `rm -rf node_modules` desde la terminal de bash.
Volver a correr el comando `pnpm install`
en caso de surgir errores corregirlos y volver a intentarlos.

Siempre previo a realizar un push asegurarse de que haya corrido el Prettier y el ESlint, se deberían ejecutar junto al commit.
Tambien se puede comprobar con el comando `pnpm prettier` y `pnpm lint`

2024-05-06 01:35 UTC, MarcosRehtanz requested changes

2024-05-06 01:35 UTC, MarcosRehtanz commented on src/molecules/SearchBarKUI/index.tsx
> +};
Agregar el parametro `placeholder?: string` para el input

2024-05-06 01:35 UTC, MarcosRehtanz commented on src/molecules/SearchBarKUI/SearchBar.stories.tsx
> +    value: '',
removerel argumento `value` que no existe en el componente

2024-05-06 01:35 UTC, MarcosRehtanz commented on src/molecules/SearchBarKUI/index.tsx
> +    // si existe la función se ejecutará
Eliminar comentario

2024-05-07 01:04 UTC, MarcosRehtanz requested changes
correr el comando `pnpm husky` antes de commitear

2024-05-07 01:04 UTC, MarcosRehtanz commented on src/molecules/SearchBarKUI/index.tsx
> +export const SearchBarKUI = ({ handleSearch, getValue, placeHolder }: SearchBarKUIProps) => {
Colocalo en minusculas `placeholder`

2024-05-07 20:20 UTC, MarcosRehtanz approved these changes

2024-05-07 20:21 UTC, merged