First Upload
kheironCo/kheiron-ui pull request #80
Opened 2024-08-22 16:11 UTC by gastonjau

2024-08-22 17:41 UTC, gastonjau commented
![image](https://github.com/user-attachments/assets/1985091f-8f11-47b8-a5f5-af55be22257c)

2024-08-22 21:01 UTC, MarcosRehtanz requested changes

2024-08-22 21:01 UTC, MarcosRehtanz commented on src/MiniModal/index.tsx
> +    items: {icon: ReactNode, text: string}[];
mover a un type a parte `type MenuItem = Parameters<typeof ButtonStyled>[0] & {
  icon: ReactNode;
  text: string
}`

2024-08-22 21:01 UTC, MarcosRehtanz commented on src/MiniModal/index.tsx
> +type DropdownButtonProps = {
cambiar `type MenuKUIProps`

2024-08-22 21:01 UTC, MarcosRehtanz commented on src/MiniModal/index.tsx
> +  export const MiniModal: React.FC<DropdownButtonProps> = ({ items , width="150px", marginLeft = "0px" }) => {
Cambiar nombre a `ModalKUI`

2024-08-22 21:01 UTC, MarcosRehtanz commented on src/MiniModal/index.tsx
> +      </div>
Comprobar en el proyecto interno `example` que el menu se sobreponga a los elementos inferirores en lugar de desplazarlos.

2024-08-22 21:01 UTC, MarcosRehtanz commented on src/MiniModal/index.tsx
> +      <div style={{marginLeft: `${marginLeft}`}}>
Utilizar el `AtomDiv`

2024-08-22 21:01 UTC, MarcosRehtanz commented on src/MiniModal/styles.tsx
> +export const ButtonIconStyled = styled.button`
utilizar el styled(AtomButton)``

2024-08-22 21:01 UTC, MarcosRehtanz commented on src/MiniModal/index.tsx
> +      </div>
Probar reducir la altura del div (componente padre)

2024-08-22 21:01 UTC, MarcosRehtanz commented on src/MiniModal/styles.css
borrar styles.css

2024-08-23 20:29 UTC, MarcosRehtanz requested changes

2024-08-23 20:29 UTC, MarcosRehtanz commented on src/ModalKUI/index.tsx
> +            {items.map((item, index) => (
```
({ icon, text, ...rest}, index)=>(
              <LiStyled key={index} items={items} index={index} {...rest}>
                   {item.icon} {item.text}
              </LiStyled>
)
```

2024-08-25 19:32 UTC, MarcosRehtanz requested changes

2024-08-25 19:32 UTC, MarcosRehtanz commented on src/MenuKUI/index.tsx
> +                          <div style={{margin: "0 10px"}}>
colocarle el `margin` al componente `LiStyled` ya que no está usando esa propiedad se puede agregar ahí en lugar de renderizar un div

2024-08-25 19:32 UTC, MarcosRehtanz commented on stories/MenuKUI/MenuKUI.stories.tsx
Borrar los comentarios 
y renombrar la exportación como está en el segundo comentario 😆

2024-08-25 19:32 UTC, MarcosRehtanz commented on example/components/TestMenuKUI/index.tsx
subir video de corto de como está interactuando

2024-08-25 20:03 UTC, gastonjau commented on example/components/TestMenuKUI/index.tsx
https://github.com/user-attachments/assets/ba5c0f1e-bce7-46db-b548-7d259cebee37

2024-08-25 20:05 UTC, gastonjau commented on example/components/TestMenuKUI/index.tsx
Puse 3 para mostrar distintas posiciones

https://github.com/user-attachments/assets/37df9a06-fa79-4b8e-a331-2d8f30a745a5

2024-08-25 20:16 UTC, merged